name: custom_catalog
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  material_color_utilities: ^0.1.4
  custom_themes:
    path: "../custom_themes"
  custom_widgets:
    path: "../custom_widgets"

  
  playbook_ui: ^0.0.3+2
  playbook: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.15.2
  build_runner: ^2.1.11
  playbook_generator: ^0.0.4  
  playbook_snapshot: ^0.1.2
  golden_toolkit: ^0.13.0


  lint: ^1.8.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

