name: core_devoops
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  # like storybook but for flutter widget isolation testing
  playbook_generator: ^0.0.4  
  playbook_snapshot: ^0.1.2
  playbook_ui: ^0.0.3+2
  playbook: ^0.0.3
  logging: ^1.0.2
  logging_appenders: ^1.0.0
  fpdart: ^0.0.14
  equatable: ^2.0.3
  kt_dart: ^0.10.0
 
  
            
 
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.15.2
  build_runner: ^2.1.11
  # better version of mockito
  mocktail: ^0.3.0
  # better goldens testing
  golden_toolkit: ^0.13.0
  # BDD testing without the hassles of integrated
  page_object: ^0.2.0
  given_when_then: ^0.2.0
  

  lint: ^1.8.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

