name: devops_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

# dependencies:
  

dev_dependencies:
  lint: ^1.8.2
  test: ^1.16.0
  dart_code_metrics: ^4.15.2
